name: envicutor

volumes:
  nix:
    external: false
  home:
    external: false
  runtimes:
    external: false

services:
  envicutor:
    build: ./envicutor
    volumes:
      - runtimes:/envicutor/runtimes
      - nix:/nix
      - home:/home/envicutor
    privileged: true
    environment:
      - PORT=5000
    healthcheck:
      test: ['CMD-SHELL', 'curl -f 127.0.0.1:5000/health || exit 1']
      interval: 3s
      timeout: 5s
      retries: 200
  test:
    build: ./test
    profiles: [test]
    depends_on:
      envicutor:
        condition: service_healthy
