volumes:
  nix:
    external: false
  runtimes:
    external: false

services:
  envicutor:
    build: ./envicutor
    volumes:
      - runtimes:/envicutor/runtimes
      - nix:/nix
    privileged: true
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - INSTALLATION_WALL_TIME=5000
      - INSTALLATION_CPU_TIME=120
      - INSTALLATION_MEMORY=10000
      - INSTALLATION_EXTRA_TIME=5
      - INSTALLATION_MAX_OPEN_FILES=256
      - INSTALLATION_MAX_FILE_SIZE=1000000
      - INSTALLATION_MAX_NUMBER_OF_PROCESSES=64
