volumes:
  nix:
    external: false
  db:
    external: false

services:
  envicutor:
    build: ./envicutor
    volumes:
      - ./envicutor/test:/submission
      - nix:/nix
    privileged: true
    cgroup: host
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
